live: True
wait_time: 60
max_events: 
batch_size: 1000
h5:
  path1: /sdf/data/lcls/ds/tmo/
  path2: /scratch/xiangli/h5/
  name1: run
  name2: .h5
log:
  path1: /sdf/data/lcls/ds/tmo/
  path2: /scratch/xiangli/log/
  
data:
  # uniform:
  #   tpks_l:
  #     len: 10
  #     var: [mcp, u1]
  #   hit_l:
  #     len: 10
  #     fvar: [n]
  #     var: [z, y, t, m]
  ragged:
  #    tpks_l:
  #    var: [mcp, u1]  
    hit_s:
      var: [z, y, t]
    hit_l:
      var: [z, y, t]      

  x:
    scan: [var1, var2]
    bld: [gmd, xgmd]
    timing: ['280','281','282','dest']
    

